<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii translation' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Documented param {param} not found in the method {method} definition' => 'Dokumentovaný parametr {param} nebyl v havičce metody {method} nalezen',
  'Input parameter {param} not found' => 'Nebyl nalezen vstupní parametr {param}',
  'Method has no phpDoc comment' => 'Metoda neobsahuje phpDoc komentář',
  'Method is not descendant of \\base\\Action' => 'Metoda není potomkem \\base\\Action',
  'Method is not intended for use via API' => 'Metoda není určena pro použití v API',
  'Method is not public' => 'Metoda není veřejná',
  'Method return type ({t1}) differs from API return type ({t2})' => 'Návratový typ metody ({t1}) se neshoduje s dokumentovaným typem ({t2})',
  'Method return type ({type}) is not supported' => 'Návratový typ metody ({type}) není podporován',
  'Method returned boolean false' => 'Metoda skončila s výsledkem boolean false',
  'Parameter {param} is not valid (validator {validator})' => 'Parametr {param} není platný (ověření {validator})',
  'Params count of the method {method} differs from phpDoc params count' => 'Počet parametrů metody {method} se liší od počtu parametrů v phpDoc',
  'Request is not secure (over HTTPS)' => 'Požadavek není bezpečný (přes HTTPS)',
  'Request method must be POST' => 'Typ požadavku musí být POST',
  'Run method is not defined for this action' => 'Pro tuto akci není definována metoda run',
  'User is not logged in' => 'Uživatel není přihlášen',
  'Validator {validator} method not found' => 'Metoda ověření {validator} nebyla nalezena',
  'You have not permission to run this action' => 'Nemáte oprávnění k použití této metody',
);
